server:
  servlet:
    context-path: /helloboot
  port: 9090

spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8

mybatis:
  type-aliases-package: com.xiaoyu.springbootdemo.domain
#  mapper-locations: classpath:mapper/*.xml
#  config-locations: classpath:**/config/mybatis-config.xml